name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: rome/setup-rome@v0.4
        with:
          version: latest

      - uses: actions/checkout@v3

      - name: Setup the project
        run: npm ci

      - name: Install rome cli tools
        run: npm install @rometools/cli-linux-x64

      - name: Run linter and format checker
        run: npm run lint

      - name: Run unit tests
        run: npm run test
