name: CI
on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup the project
        run: yarn

      - name: Run linter and format checker
        run: yarn lint

      - name: Create a build
        run: yarn build

      - name: Run unit tests
        run: yarn test
