name: CI
on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # setup Bun for runtime tests
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: taiki-e/install-action@v2
        with:
          tool: biome,just

      - name: Run linter and format checker
        run: just lint

      - name: Create builds
        run: just build-all

      - name: Run all tests
        run: just test-all
