name: CI
on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: biomejs/setup-biome@v1

      # setup Bun for runtime tests
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: taiki-e/install-action@just

      - name: Setup the project
        run: yarn

      - name: Run linter and format checker
        run: yarn lint

      - name: Create a build
        run: yarn build

      - name: Run unit tests
        run: yarn test
