name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: rome/setup-rome@v0.4
        with:
          version: latest

      - uses: actions/checkout@v3

      - name: Setup the project
        run: yarn --immutable

      - name: Run linter and format checker
        run: yarn lint

      - name: Run unit tests
        run: yarn test
