name: Publish TypeScript plugin package to NPMJS
on:
  push:
    tags:
      - "typescript-plugin-*"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: rome/setup-rome@v0.4
        with:
          version: latest

      - uses: actions/checkout@v3

      - name: Setup the project
        run: npm ci

      - name: Install rome cli tools
        run: npm install @rometools/cli-linux-x64

      - name: Run linter and format checker
        run: npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: "@autometrics"

      - run: npm ci

      - run: npm run build --workspace=@autometrics/typescript-plugin
      - run: npm run release --workspace=@autometrics/typescript-plugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

