name: Publish TypeScript plugin package to NPM
on:
  push:
    tags:
      - "typescript-plugin-*"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup the project
        run: yarn --immutable

      - name: Run linter and format checker
        run: yarn lint

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: "@autometrics"

      - run: yarn --immutable

      - run: yarn build --workspace=@autometrics/typescript-plugin

      - run: yarn release --workspace=@autometrics/typescript-plugin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

