name: Publish main @autometrics/autometrics and the exporters to NPM
on:
  push:
    tags:
      - "lib-*"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # setup Bun for runtime tests
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup the project
        run: yarn

      - name: Run linter and format checker
        run: yarn lint

      - name: Run unit tests
        run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: "@autometrics"

      - run: yarn

      - run: yarn build

      - run: yarn release-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
