name: Publish Parcel transformer plugin package to NPM
on:
  push:
    tags:
      - "parcel-transformer-*"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup the project
        run: yarn

      - name: Run linter and format checker
        run: yarn lint

      - name: Run unit tests
        run: yarn test

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: "@autometrics"

      - run: yarn

      - run: yarn build --workspace=@autometrics/parcel-transformer-autometrics

      - run: yarn release --workspace=@autometrics/parcel-transformer-autometrics
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

